// Generated by CoffeeScript 1.8.0
(function() {
  var assert, base58, nacl, pink, pubkey, suite, vows;

  pink = require('../pink-net');

  vows = require('vows');

  assert = require('assert');

  nacl = require('tweetnacl/nacl-fast');

  base58 = require('bs58');

  suite = vows.describe('Pink Network Utilities');

  pubkey = nacl.randomBytes(32);

  suite.addBatch({
    "Pink Invite Generation": {
      topic: new pink.Invite({
        address: "1.2.3.4",
        port: 5678,
        publicKey: pubkey
      }),
      "constructs something": function(invite) {
        assert.isString(invite.toString());
        return assert.isTrue(invite.toString().length !== 0);
      },
      "verifies": function(invite) {
        return assert.isTrue(pink.Invite.verify(invite.toString()));
      },
      "corrupted doesn't verify": function(invite) {
        return assert.isFalse(pink.Invite.verify(invite.toString() + "a"));
      },
      "parsing works": function(invite1) {
        var invite2;
        invite2 = new pink.Invite(invite1.toString());
        return assert.equal(invite1.inspect(), invite2.inspect());
      }
    }
  });

  suite.run();

}).call(this);
