// Generated by CoffeeScript 1.8.0
(function() {
  var address, base58, help, invite;

  base58 = require('bs58');

  help = require('./helpers');

  address = require('./address');

  invite = (function() {
    function invite(opts) {
      this.address = opts.address || new address(opts);
    }

    invite.prototype.toString = function() {
      var addr, check;
      addr = this.address.toBuffer();
      check = help.blake(addr, 1);
      return base58.encode(Buffer.concat([check, addr]));
    };

    return invite;

  })();

  invite.verify = function(inviteCode) {
    var bytes, err;
    try {
      bytes = base58.decode(inviteCode);
    } catch (_error) {
      err = _error;
      return false;
    }
    return help.blake(bytes.slice(1), 1)[0] === bytes[0];
  };

  invite.parse = function(inviteCode) {
    var addr, bytes;
    bytes = base58.decode(inviteCode);
    if (help.blake(bytes.slice(1), 1)[0] !== bytes[0]) {
      return false;
    }
    addr = address.parse(help.asBuffer(bytes.slice(1)));
    if (!addr) {
      return false;
    }
    return new invite({
      address: addr
    });
  };

  module.exports = invite;

}).call(this);
